---
title: "MSD Homework 4, Problem 3"
author: "Mia Fyrer (mzf2106)"
date: '`r Sys.time()`'
output:
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(here)
library(scales)
library(igraph)
library(tidyverse)
library(modelr)
library(ggplot2)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)

```

# Part A



```{r read in paper data}

business_edglist <- read.table(
  file = "Dataset 1. Business_edgelist.txt", 
                                header=T, sep="")
business_vertexlist <- read.table(
  file = "Dataset 2. Business_vertexlist.txt", 
                                header=T, sep='\t')
computer_science_edglist <- read.table(
  file = "Dataset 3. ComputerScience_edgelist.txt",
                                header=T, sep="")
computer_science_vertexlist <- read.table(
  file = "Dataset 4. ComputerScience_vertexlist.txt", 
                                header=T, sep='\t')
history_edglist <- read.table(
  file = "Dataset 5. History_edgelist.txt",
                                header=T, sep="")
history_vertexlist <- read.table(
  file = "Dataset 6. History_vertexlist.txt", 
                                header=T, sep='\t')


```

#

```{r plot-neighbors-vs-node}

total_placements_biz <- business_edglist %>%
  filter(u<n()) %>%
  summarise(rows=n())
total_placements_biz <- as.numeric(total_placements_biz)

placement_data_biz <- business_edglist %>%
  filter(u<n()) %>%
  group_by(u) %>%
  summarise(faculty_produced_biz=n(),
            fraction_placements_biz=n()/total_placements_biz) %>%
  arrange(desc(fraction_placements_biz)) %>%
  mutate(cum_place_percent_biz=cumsum(fraction_placements_biz)) %>%
  mutate(fraction_schools_biz=row_number()/n())


total_placements_cs <- computer_science_edglist %>%
  filter(u<n()) %>%
  summarise(rows=n())
total_placements_cs <- as.numeric(total_placements_cs)

placement_data_cs <- computer_science_edglist %>%
  filter(u<n()) %>%
  group_by(u) %>%
  summarise(faculty_produced_cs=n(),
            fraction_placements_cs=n()/total_placements_cs) %>%
  arrange(desc(fraction_placements_cs)) %>%
  mutate(cum_place_percent_cs=cumsum(fraction_placements_cs)) %>%
  mutate(fraction_schools_cs=row_number()/n())


total_placements_hs <- history_edglist %>%
  filter(u<n()) %>%
  summarise(rows=n())
total_placements_hs <- as.numeric(total_placements_hs)

placement_data_hs <- history_edglist %>%
  filter(u<n()) %>%
  group_by(u) %>%
  summarise(faculty_produced_hs=n(),
            fraction_placements_hs=n()/total_placements_hs) %>%
  arrange(desc(fraction_placements_hs)) %>%
  mutate(cum_place_percent_hs=cumsum(fraction_placements_hs)) %>%
  mutate(fraction_schools_hs=row_number()/n())

x <- c(0,.5,1)
y <- c(0,.5,1)
equality_line <- data.frame(x,y)

ggplot()+
  geom_point(data = placement_data_cs, 
             aes(x=fraction_schools_cs,y=cum_place_percent_cs, color="Computer Science"))+
  geom_line(data = placement_data_cs, 
             aes(x=fraction_schools_cs,y=cum_place_percent_cs, color="Computer Science"))+
  geom_point(data = placement_data_biz, 
             aes(x=fraction_schools_biz,y=cum_place_percent_biz, color="Business"))+
  geom_line(data = placement_data_biz, 
             aes(x=fraction_schools_biz,y=cum_place_percent_biz, color="Business"))+
  geom_point(data = placement_data_hs, 
             aes(x=fraction_schools_hs,y=cum_place_percent_hs, color="History"))+
  geom_line(data = placement_data_hs, 
             aes(x=fraction_schools_hs,y=cum_place_percent_hs, color="History"))+
  scale_x_continuous(breaks = seq(0, 1, by = 0.25))+
  scale_y_continuous(breaks = seq(0, 1, by = 0.1))+
  geom_abline(intercept = 0,slope = 1)+
  geom_text(aes(x = .5, y = .55, label = "Equality line", angle = 40))+
  geom_area(data=equality_line, aes(x=x, y=y), fill="#D3D3D3")+
  xlab("Fraction of institutions")+
  ylab("Fraction of faculty produced")
  
  
```




